### ISSUE TITLE
Look forward to use this web framework

### ISSUE THREAD

**Issue by mgadikota-rpx** [CapsicoHealth/WandA-X#1]
Hi @ldhasson,
    I'm looking forward to use and make contributions to this framework. Is there any timeline when you could roleout initial version of this framework ?

**Comment by ldhasson** [comment]
We are talking a few weeks. I am almost done and working on removing all traces of Capsico-specific stuff... The issue is that the PEOPLE schemd is used for managing both users (which do belong in this framework), and Patients (which are part of Capsico's proprietary clinical schema). I have to complete that cleanup before moving things out.

**Comment by mgadikota-rpx** [comment]
okay, thank you for info @ldhasson
